# Generated by Django 3.0.6 on 2020-08-06 03:45

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200802_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.jpg', upload_to=users.models.get_upload_path, verbose_name='profile image'),
        ),
    ]
